### ISSUE TITLE
Failure with dev testthat

### ISSUE THREAD

**Issue by hadley** [gregfrog/brew#1]
```
> library(testthat)
> library(brew)
> 
> test_that("error report produces stack trace (or not)", {
+   anotherStackLayer<-function(){
+     yetAnotherStackLayer<-function()
+     {
+       brew("error.brew",envir = new.env(),extendedErrorReport = TRUE)
+     }
+     yetAnotherStackLayer()
+   }
+   
+   local_edition(3)
+   expect_snapshot(anotherStackLayer(), variant = "extraStackLayers")
+   expect_snapshot(brew("error.brew",envir = new.env(),extendedErrorReport = TRUE), variant = "extErr")
+   expect_snapshot(brew("error.brew",envir = new.env(),extendedErrorReport = FALSE), variant = "noextErr")
+   expect_snapshot(brew("error.brew",envir = new.env()), variant = "noextErrparm")
+ })
── Error ('/Users/hadleywickham/Documents/devtools/testthat/R/snapshot.R:100'): error report produces stack trace (or not) ──
<rlib_error_3_0/rlib_error/error/condition>
Error in `"lapply(text, glue_cmd, .envir = .envir)"`: ! Could not parse cli `{}` expression: ` anotherStackLay…`.
Caused by error in `parse(text = code, keep.source = FALSE)`:
! <text>:1:176: unexpected symbol
1:     anotherStackLayer <- function() {        yetAnotherStackLayer <- function() {            brew("error.brew", envir = new.env(), extendedErrorReport = TRUE)        }        yetAnotherStackLa
                                                                                                                                                                                   ^
Backtrace:
  1. testthat::expect_snapshot(anotherStackLayer(), variant = "extraStackLayers")
 25. base::.handleSimpleError(...)
 26. h(simpleError(msg, call))
 27. throw_error(err, parent = e)
```

This seems like a possible testthat bug but I can't easily reproduce it outside of `R CMD check`, and I don't understand what the intent of this code is. Do you think you could try and create a simpler reprex for me? I really would like to be able to submit a patch version of testhat to CRAN in the near future, so I'd really appreciate it if you could take a look.

**Comment by gregfrog** [comment]
Hadley, the intent of the test code is to add some aditional height to the stack trace.  The intent of the switch which is being tested is to turn on or off behaviour in the internal error handling routine that suppresses writing out the brew internal calls in the stack trace when an error occurs.    

The runtime behaviour in that test case is the series of calls that you can see, an error handler is established inside brew, then brew makes some more calls defined in the error.brew template, at the bottom a call is made to an undefined function which triggers the brew-internal error handler.  I don't know what the testthat error handler is doing or why its parsing the code in the call stack.   I have seen odd interactions with the testthat error handling before, but that was some time ago.

**Comment by gregfrog** [comment]
The code that prints the call stack gets the stack from Sys.calls and assigns it to a variable in a local environment.  It does modify the return value from withCallingHandlers, but that doesn't look like your problem.  

tryWithStackTrace <- function(exp)
  {
    tryenv <- new.env()
    assign("stackDepthAtEntry", value=length(sys.calls()), envir=tryenv)
    out <- try(withCallingHandlers(exp, error=function(e)
    {
      stackDepthAtEntry = get("stackDepthAtEntry",envir=tryenv)
      stack <- sys.calls()
      stack <- head(stack, -2)
      stack <- sapply(stack, deparse)
      if(isTRUE(getOption("show.error.messages"))) 
      {
        message("Call stack at error:")
        for(m in head(stack, stackDepthAtEntry-2))
        {
          message("\t",m)
        }
        message("\t ...")
        for(m in tail(stack, (-1 * stackDepthAtEntry)-8))
        {
          message("\t",m)
        }
      }
      assign("stack", value=paste(stack,collapse="\n"), envir=tryenv)
    }), silent=!isTRUE(getOption("show.error.messages")))
    if(inherits(out, "try-error")) out[2] <- tryenv$stack
    out
  }

**Comment by gregfrog** [comment]
I've sent the update to CRAN incorporating your PR and some other changes.  I've hard coded the test case to only look at the head and tail of the stack trace message, thus avoiding the testthat entries and commented out the HTML generation that was just too, too fragile.  

I am slightly nervous about an issue you have open from a bioconductor package (updateObject) suggesting that there may be an issue with using capture.output(type="message") but for the moment the code (which uses capture.output to get the messages to filter out the testthat entries) is working.
